resource_group_name = "rg-mofoaks"
location = "australiaeast"
tags = {
  environment = "dev"
  owner = "willmofo"
  application = "mofoaks"
  location = "centralus"
}
user_assigned_identity_name = "dev-uai-mofoaks"
acr_name = "devacrmofoaks"
vm_size = "Standard_D2s_v3"
aks_username = "willmofo"
aks_name = "dev-mofoaks"
azure_monitor_workspace_name = "dev-amw-mofoaks"
grafana_name = "dev-grafana-mofoaks"